[package]
name = "pyfmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xshell = "0.2.3"
anyhow = "1"
sled = "0.34.7"
